### ISSUE TITLE
what about llm responses mean

### ISSUE THREAD

**Issue by Everfighting** [JazBern/LMDX-flow#1]
Code did work out, Please kindly help me to solve it .
```
## Load the tokenizer
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

from lmdx_flow import Pipeline
P = Pipeline(file_path,tokenizer)
prompts = P.generate_prompt(schema)
answers = P.postprocess_all_chunks(llm_responses)
```
schema did not define, I know it is the entity json I try to extract. 
what about llm responses mean? How can I create it .

**Comment by JazBern** [comment]
llm_responses is the LLM output for a given prompt. It is obtained by passing the generated prompt to an LLM.

**Comment by Everfighting** [comment]
OK, thanks.
